[build]
builder = "nixpacks"

[deploy]
startCommand = "python ai_server/run_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
PORT = "5003"
FLASK_ENV = "production"
FLASK_DEBUG = "false" 